AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  ejemplo-Raul-sam-app

  Sample SAM Template for ejemplo-Raul-sam-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Runtime: python3.12
    Architectures:
      - x86_64
    Handler: app.lambda_handler
    EphemeralStorage:
      Size: 1000
    Environment:
      Variables:
        ATLAS_URI: mongodb+srv://aantonioramirez33:Bj6JzCUcaMtEysM1@clustertelemetry.lifiiiu.mongodb.net/?retryWrites=true&w=majority&appName=ClusterTelemetry
        DB_TEST: Test

Resources:
  ## Lambdas roles
  RaulLambdasRole:
    Type: AWS::IAM::Role
    Properties:
      Description: For allow lambdas execute their tasks.
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonDMSCloudWatchLogsRole
        - arn:aws:iam::aws:policy/AmazonEventBridgeFullAccess
        # - arn:aws:iam::aws:policy/AmazonEventBridgeSchedulerFullAccess
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AmazonSQSFullAccess
        - arn:aws:iam::aws:policy/AmazonEC2FullAccess
        - arn:aws:iam::aws:policy/AmazonVPCFullAccess
        - arn:aws:iam::aws:policy/service-role/AWSCodeDeployRoleForLambda
        - arn:aws:iam::aws:policy/AWSLambda_FullAccess
        - arn:aws:iam::aws:policy/AWSLambdaExecute
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
      RoleName: RaulLambdasRole

  # SOURCES
  BucketRaulTest:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: bucket-raul-test-1107200121

  # QUEUE Policies
  # Policy for S3 event notification
  RaulS3EventNotificationPolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref RaulNewJsonsQueue
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: example-statement-ID
            Effect: Allow
            Principal:
              Service: "s3.amazonaws.com"
            Action:
              - "sqs:SendMessage"
            Resource: !GetAtt RaulNewJsonsQueue.Arn
            Condition:
              ArnLike:
                aws:SourceArn: !GetAtt BucketRaulTest.Arn
              StringEquals:
                aws:SourceAccount: "665531541875"

  # # QUEUES
  RaulNewJsonsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: RaulNewJsonsQueue
      MessageRetentionPeriod: 86400 # seconds (1 day)
      VisibilityTimeout: 2400 # seconds (40 min)

  # # LAMBDAS
  RaulSaveJsonOnMongoDB:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: raul_save_json_on_mongo_db/
      MemorySize: 1024
      Timeout: 60
      Role: !GetAtt RaulLambdasRole.Arn
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt RaulNewJsonsQueue.Arn
            BatchSize: 100
            Enabled: true
            MaximumBatchingWindowInSeconds: 10
            ScalingConfig:
              MaximumConcurrency: 2
      Environment:
        Variables:
          MY_COLLECTION: raul_collection
          LAMBDA_HELLO_WORLD: !GetAtt raulHelloWorld.Arn

  raulHelloWorld:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: raul_hello_word/
      MemorySize: 512
      Timeout: 20
      Role: !GetAtt RaulLambdasRole.Arn

Outputs:
  BucketRaulTest:
    Value: !Ref BucketRaulTest
    Description: "Nombre del bucket S3 que enviará notificaciones a la cola SQS"

  RaulNewJsonsQueue:
    Value: !Ref RaulNewJsonsQueue
    Description: "URL de la cola SQS donde se recibirán las notificaciones"
